#!/usr/bin/env bash

(
  set -e
  set -u

  export _BASE_CONFIG_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
  . functions

  # things I expect to have at my fingertips

  command-exists vim || sudo apt install -y vim
  command-exists git || sudo apt install -y git

  for file in "${_BASE_CONFIG_DIR}/steps"/*.sh
  do
    echo "Applying $file..."
    bash "$file"
  done 
)
